default: &default
  adapter: trilogy
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  socket: <%= ENV["DB_SOCKET"] %>

development:
  <<: *default
  database: silva_numerica_oauth_provider_development

test:
  <<: *default
  database: silva_numerica_oauth_provider_development

production:
  <<: *default
  database: silva_numerica_oauth_provider_production
  username: <%= Rails.application.credentials.dig(:production, :database_user) %>
  password: <%= Rails.application.credentials.dig(:production, :database_pass) %>
